# Generated by Django 2.1.5 on 2019-02-05 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesinformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesinformation',
            name='guidelines',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='大会要項'),
        ),
        migrations.AlterField(
            model_name='gamesinformation',
            name='result',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf '])], verbose_name='大会結果'),
        ),
    ]
