# Generated by Django 2.1.5 on 2019-02-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=50, verbose_name='所属県連')),
                ('category', models.CharField(max_length=10, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名前')),
                ('birth', models.DateTimeField(verbose_name='生年月日')),
                ('team', models.CharField(max_length=30, verbose_name='チーム名')),
                ('school', models.CharField(max_length=255, verbose_name='出身校')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('pic', models.TextField(verbose_name='URL')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playerprofile.Info', verbose_name='情報')),
            ],
        ),
    ]
