# Generated by Django 2.1.5 on 2019-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='which',
            field=models.CharField(blank=True, max_length=10, verbose_name='リンクorロード'),
        ),
    ]
