# Generated by Django 2.1.5 on 2019-02-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_category_which'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRoadMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRoadWoman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRoadWorldMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRoadWorldWoman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTrackWorldMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTrackWorldWoman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='RecordWoman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=40, verbose_name='距離')),
                ('who', models.CharField(max_length=40, verbose_name='記録保持者')),
                ('team', models.CharField(max_length=40, verbose_name='チーム名or出身')),
                ('time', models.CharField(max_length=40, verbose_name='タイム')),
                ('created_at', models.DateTimeField(verbose_name='開催日')),
                ('where', models.CharField(max_length=40, verbose_name='開催地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='record.Category', verbose_name='カテゴリ')),
            ],
        ),
    ]
